Feat/login
YAPP-Github/FullCar-iOS pull request #1
Opened 2023-12-17 21:25 UTC by SunnnySong

## 로그인 구현 

### 구현 내용
#### 로그인 객체 별 역할
- **FullCarKit/Sources/Account**
    - `API/AccountAPI` : 사용자 계정과 관련된 API 호출(네트워크 통신)
    - `Model/AccountCredential` : 자체 토큰 타입
    - `AccountService` : 사용자 계정 관리 역할
        - hasValidToken: 토큰이 존재하고, 기간이 유효한지 
        - login: 서버로 access token을 전달하고, 로그인에 성공하면 tokenStorage에 서비스 자체 토큰 타입인 AccountCredential 저장
        - logout: 로그아웃
        - leave: 회원 탈퇴 후 tokenStorage에서 토큰 삭제
- **FullCarKit/Sources/Network**
    - `Token/TokenStorage` : 서비스 자체 토큰인 AccountCredential을 Keychain으로 관리
- **FullCar/Sources/Login**
    - Login : 카카오/애플 로그인 구현
        - 클린 아키에서 Usecase와 같은 역할로 생각하고 구현함
  
 #### Kakao API 초기 설정
- Dependencies에 카카오 로그인 관련 SDK 추가
- 카카오 로그인 기본 설정을 위한 Info plist 수정
- 카카오 앱 키를 깃헙에 올리는 것을 막기 위한 xcconfig 설정
    - APIKeys 라는 xcconfig 파일을 생성해 FullCar/Resources 하위에 추가
    - .gitignore에 .xcconfig 추가
    - 키 값을 간편하게 가져오기 위한 Bundle extension 추가 

#### ViewModel에서 @Dependency 오류
- Property wrapper cannot be applied to a computed property 오류 발생
```swift
@MainActor
@Observable
final class LoginViewModel {
    @Dependency(\.login) var login
}
```
- @Observable는 모든 속성이 default value를 가져야 함.
- 해당 속성은 관찰할 필요가 없도록 @ObservationIgnored 추가해 오류 해결

### 궁금한 점
- 카카오 앱 키와 같은 API Key를 관리하는 APIKeys의 위치는 FullCar/Resources 하위에 있는 것이 적절한가요!?!!

2023-12-18 03:57 UTC, havilog requested changes
주말 갈아 넣었을 선화에게 박수를..!

2023-12-18 03:57 UTC, havilog commented on Targets/FullCar/Sources/FullCarApp.swift
> +                }
요거 혹시 RootView의 body에 달아도 되는거면 init 시점에 setupKakaoSDK를 하기보단 RootViewModel에서 해주는게 나을거 같을듯

2023-12-18 03:57 UTC, havilog commented on Targets/FullCar/Sources/Login/Login.swift
> +    func kakaoLogin(completion: @escaping () -> Void) async {
completion 말구 async로 해줄 수 있으려나?!

2023-12-18 03:57 UTC, havilog commented on Targets/FullCar/Sources/Login/Login.swift
> +    @Dependency(\.accountService.login) var login
Login에서 디펜던시로 login을 물고 있어서 좀 헷갈리는듯
FullCarAccount, FCAccount..., Account 등등 다른 이름은 어떨라나

2023-12-18 03:57 UTC, havilog commented on Targets/FullCar/Sources/Login/Login.swift
> +    func kakaoLogin(completion: @escaping () -> Void) async {
```suggestion
    func kakaoLogin() async throws {
```

2023-12-18 03:57 UTC, havilog commented on Targets/FullCar/Sources/Login/Login.swift
> +            }
async에서는 DispatchQueue 쓰면 안됨
떱씨 어딘가에 나와있는데 링크는 못찾겠지만
함수에 @MainActor 달아주세용

2023-12-18 03:57 UTC, havilog commented on Targets/FullCar/Sources/Login/Login.swift
> +            }
혹시 카카오 SDK 자체에서 async 인터페이스는 지원 안해주나?
해준다면 그 인터페이스로 쓰면 좋을거 같고
안해준다면 completion이 한 번만 불리는지 확인해주는 코드가 있으면 좋을듯
withCheckedThrowingContinuation 두번 불리면 크래시라서

2023-12-18 03:57 UTC, havilog commented on Targets/FullCarKit/Sources/Account/AccountService.swift
> +                let response = api.login(accessToken)
response를 Result로 안받고 login을 throwing하는 함수로 해줘도 될 듯

2023-12-18 03:57 UTC, havilog commented on Targets/FullCarKit/Sources/Account/Model/AccountCredential.swift
> +    var authTokenExpiration: Date
엑세스 토큰이랑 리프레쉬 토큰이랑 나눠야하지 않을까?

2023-12-18 03:57 UTC, havilog commented on Targets/FullCarKit/Sources/Account/Model/AccountCredential.swift
> +    var authToken: String
+ 프로퍼티들은 let이어도 될 듯

2023-12-18 03:57 UTC, havilog commented on Targets/FullCarKit/Sources/Network/Token/TokenStorage.swift
> +    private let key = "accountCredential"
요런건 static이어도 좋을 듯

2023-12-18 03:57 UTC, havilog commented on Targets/FullCarKit/Sources/Network/Token/TokenStorage.swift
> +struct TokenStorage {
요거 actor 써봐도 좋을 듯? (나도 안써봄)

2023-12-18 05:23 UTC, ITlearning requested changes
주말 내내 고생 많았어 ㅠㅠㅜㅠㅠㅠ
형이 좋은 피드백을 많이 해줘서 나는,,,나중에 스유 관련 문제 있으면 더 코멘트 달아줄게!

Swift-Dependencies 라이브러리는 나도 처음 해보는거라서 같이 잘 해보자굿 💪

개발자 계정 저거 로그인 관련 옵션 키는거 말하는거지? 내가 해볼게!

2023-12-18 05:23 UTC, ITlearning commented on Targets/FullCarKit/Sources/Network/Token/TokenStorage.swift
> +        self.deleteToken()
꼭 self 써야 하는 상황 아니면 제거해도 좋을듯!

2023-12-18 05:23 UTC, ITlearning commented on Targets/FullCar/Sources/FullCarApp.swift
> +                    }
```swift
if (AuthApi.isKakaoTalkLoginUrl(url)) {
     _ = AuthController.handleOpenUrl(url: url)
}
```
이거 함수로 따로 뺄 수 있으면 빼는 것도 좋아보여욤
(근데 이건 코드 스타일이긴 한듯)

2023-12-19 07:14 UTC, SunnnySong commented on Targets/FullCar/Sources/FullCarApp.swift
> +                }
수정했습니다~
> 커밋: 5e268ddc06f6ba79fd5b09ff00f65dffe77fe97d

2023-12-19 07:23 UTC, SunnnySong commented on Targets/FullCar/Sources/FullCarApp.swift
> +                    }
오 좋아요!
> 커밋: d512e45d813c7f3f4cd022d1d26e7698dbd1a65c

2023-12-19 13:58 UTC, SunnnySong commented on Targets/FullCar/Sources/Login/Login.swift
> +    @Dependency(\.accountService.login) var login
오, 다시 보니깐 이름이 겹쳐 헷갈릴거같네용
수정했습니다!
> 커밋: 3c03f026914b65caf03324da392927240ee89730

2023-12-19 19:40 UTC, SunnnySong commented on Targets/FullCar/Sources/Login/Login.swift
> +            }
async에 대해 자세히 공부해봐야겟숩니다,, 허허

2023-12-19 19:48 UTC, SunnnySong commented on Targets/FullCar/Sources/Login/Login.swift
> +            }
카카오 SDK에서는 async를 지원하지 않아여,,😭

```swift
final class FullCarAccount {
    // ...
    private var continuation: CheckedContinuation<String, Error>?

    @MainActor
    func kakaoLogin() async throws {
        if self.continuation == nil {
            let accessToken: String = try await withCheckedThrowingContinuation { continuation in
                authenticateWithKakao()
                self.continuation = continuation
            }
            try login(accessToken)
        } else {
            throw LoginError.continuationAlreadySet
        }
    }

    // ...

    private func authenticateWithKakao() {
        let completion: ((OAuthToken?, Error?) -> Void) = { token, error in
            if let error = error {
                self.continuation?.resume(throwing: error)
            } else {
                guard let accessToken = token?.accessToken else {
                    self.continuation?.resume(throwing: LoginError.kakaoTokenNil)
                    return
                }
                self.continuation?.resume(returning: accessToken)
            }
        }

        if UserApi.isKakaoTalkLoginAvailable() {
            UserApi.shared.loginWithKakaoTalk(completion: completion)
        } else {
            UserApi.shared.loginWithKakaoAccount(completion: completion)
        }
    }
}
```

이런 식으로 구현하면 어떨까요??

2023-12-19 19:49 UTC, SunnnySong commented on Targets/FullCar/Sources/Login/Login.swift
> +    func kakaoLogin(completion: @escaping () -> Void) async {
아래 continuation 관련 코멘트에서 모두 수정하였습니다~

2023-12-19 19:51 UTC, SunnnySong commented on Targets/FullCarKit/Sources/Account/Model/AccountCredential.swift
> +    var authToken: String
오, 그러네요!

> 커밋: e31e14e41bf2ea8baae21acd684a2629b7447a31

2023-12-19 19:56 UTC, SunnnySong commented on Targets/FullCarKit/Sources/Account/AccountService.swift
> +                let response = api.login(accessToken)
오 좋아요. 그럼 AccountService에서 네트워크 호출하는 코드 작성할 때 같이 수정하겠습니다~

2023-12-21 08:50 UTC, SunnnySong commented on Targets/FullCarKit/Sources/Account/Model/AccountCredential.swift
> +    var authTokenExpiration: Date
아, 그러네용. 수정했어요!!

> 커밋: 878b73c168ee8c6effd4de9a1b885d501b385b54

2023-12-21 14:47 UTC, SunnnySong commented on Targets/FullCarKit/Sources/Network/Token/TokenStorage.swift
> +struct TokenStorage {
짱 좋은 생각입니다,,,, 

> 커밋: f1cf9c5838aa1ff742167dcf69b1c7488849aeda

2023-12-30 16:31 UTC, merged